config/routes.rb
Rails.application.routes.draw do
  root 'application#landing'
  get '/profiles', to: 'application#index',  as: 'profiles'
  get '/account-type', to: 'application#account_type'
  get '/about', to: 'application#about'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :searches, except: [:index, :update, :destroy]
  resources :people, :cats, except: [:index]
  #show? 'Profiles/:id/cat'
  #show? 'Profiles/:id/adopter'
  resources :admins, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  validates :name, presence: true
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  validates :name, presence: true
  has_many :person_cats
  has_many :persons, through: :person_cats

end

app/models/person.rb
class Person < ApplicationRecord
  validates :name, presence: true
  has_secure_password
  has_many :person_cats
  has_many :cats, through: :person_cats
end

app/models/person_cat.rb
class PersonCat < ApplicationRecord
  belongs_to :cat
  belongs_to :person

  def self.search(params)
    params.keys.each do |key|
      
    end
  end
end

app/models/search.rb
class Search < ApplicationRecord

  def search_profiles
    cats = cats_search
    people = people_search

    profiles = []

    if !cats.nil?
      profiles += cats
    end

    if !people.nil?
      profiles += people
    end

    return profiles

  end

  def cats_search
    cats = Cat.all
    # cats = Cat.where("name LIKE ? OR description LIKE ? OR location LIKE ? OR age = ? OR breed LIKE ? or temperament LIKE ? OR sociability LIKE ?", "%#{name}%", "%#{description}%", "%#{location}%", age, "%#{breed}%", "%#{temperament}%", "%#{sociability}%")
    cats = cats.where("name LIKE ?", "%#{name}%") if name.present?
    cats = cats.where("description LIKE ?", "%#{description}%") if description.present?
    cats = cats.where("location LIKE ?", "%#{location}%") if location.present?
    cats = cats.where("age = ?", age) if age.present?
    cats = cats.where("breed LIKE ?", "%#{breed}%") if breed.present?
    cats = cats.where("temperament LIKE ?", "%#{temperament}%") if temperament.present?
    cats = cats.where("sociability LIKE ?", "%#{sociability}%") if sociability.present?

    if cats == Cat.all
      return nil
    else
      return cats
    end
  end

  def people_search
    people = Person.all

    people = people.where("name LIKE ?", "%#{name}%") if name.present?
    people = people.where("description LIKE ?", "%#{description}%") if description.present?
    people = people.where("location LIKE ?", "%#{location}%") if location.present?

    people = people.where("min_age_pref = ?", min_age_pref) if min_age_pref.present?
    people = people.where("max_age_pref = ?", max_age_pref) if max_age_pref.present?
    people = people.where("breed_pref LIKE ?", "%#{breed_pref}%") if breed_pref.present?
    people = people.where("temperament_pref LIKE ?", "%#{temperament_pref}%") if temperament_pref.present?
    people = people.where("num_of_cats = ?", num_of_cats) if num_of_cats.present?

    if people == Person.all
      return nil
    else
      return people
    end

  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      redirect_to profiles
    else
      render 'new'
    end
  end

  private

  def admin_params
    params.require(:admin).permit(:name, :password, :password_field)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in
  helper_method :current_user

  def logged_in?
    !session[:person_id].nil?
  end

  def landing
  end

  def index
    @profiles = Person.all + Cat.all
    if params[:search]
      @profiles = params[:search].constantize.all
    else
      @profiles = Person.all + Cat.all
    end
  end

  def about

  end

  def account_type
  end

  def current_user
    @current_user ||= Person.find(session[:person_id])
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  # def method_name
  #   person = Person.find(session[:person_id])
  #   cat.persons.includes?(person)
  # end

  def new
    @cat = Cat.new
  end

  def show

    if !logged_in?
      redirect_to login_path
    end
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.valid?
      person = Person.find(session[:person_id])
      person.cats << @cat
      @cat.save
      redirect_to @cat
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @cat.update(cat_params)
    if @cat.save
      redirect_to @cat
    else
      render 'edit'
    end
  end

  def destroy
    @cat.delete
    redirect_to profiles
  end

  private

  def set_cat
    @cat = Cat.find(params[:id])
  end

  def cat_params
    params.require(:cat).permit(:name, :age, :description, :location, :breed, :temperament, :sociability, :image_url)
  end
end

app/controllers/concerns/adopters_controller.rb
class AdoptersController < ApplicationController
  before_action :set_adopter, only: [:show, :edit, :update, :destroy]

  def new
    @adopter = Adopter.new
  end

  def show
  end

  def create
    @adopter = Adopter.new(adopter_params)
    if @adopter.save
      redirect_to @adopter
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @adopter.update(adopter_params)
    if @adopter.save
      redirect_to @adopter
    else
      render 'edit'
    end
  end

  def destroy
    @adopter.delete
    redirect_to profiles
  end

  private

  def set_adopter
    @adopter = Adopter.find(params[:id])
  end

  def adopter_params
    params.require(:adopter).permit(:name, :email, :password, :password_confirmation, :age, :description, :location, :min_age_pref, :max_age_pref, :breed_pref, :temperament_pref, :num_of_cats, :image_url)
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :check_person_id, only: [:edit, :update, :destroy]
  before_action :require_login, except:[:new, :create]

  def new
    @person = Person.new
  end

  def show

  end

  def create
    @person = Person.new(person_params)
    if @person.save
      session[:person_id] = @person.id
      redirect_to @person
    else
      flash[:error] = @person.errors.full_messages
      redirect_to new_person_path
    end
  end

  def edit

  end

  def update
    @person.update(person_params)
    if @person.save
      redirect_to @person
    else
      flash[:error] = @person.errors
      render 'edit'
    end
  end

  def destroy
    @person.delete
    redirect_to root_path
  end

  private

  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:name, :email, :password, :password_confirmation, :age, :description, :location, :min_age_pref, :max_age_pref, :breed_pref, :temperament_pref, :num_of_cats, :image_url, :admin)
  end

  def check_person_id
    unless session[:person_id] == @person.id || Person.find(session[:person_id]).admin?
      redirect_to login_path
    end
  end

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to login_path # halts request cycle
    end
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new
  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
    # render "application/index"
  end

  private

  def search_params
    params.require(:search).permit(:name, :age, :description, :location, :breed, :temperament, :sociability, :min_age_pref, :max_age_pref, :breed_pref, :temperament_pref, :num_of_cats)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

    if logged_in?
      redirect_to profiles_path
    end
  end

  def create
    person = Person.find_by(email: params[:email])
    if person && person.authenticate(params[:password])
      session[:person_id] = person.id
      redirect_to person
    else
      flash[:error] = 'Invalid email/password combination'
      redirect_to login_path
    end
  end

  def destroy
    session[:person_id] = nil

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admins/new.html.erb
<%= form_for @admin do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :email %><br>
  <%= f.text_field :email %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/application/about.html.erb
<body class="contact">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <div class="container">
    <div class="bg-light text-dark">
      <div class="col-lg-3">

        <h1>About</h1>

        <p>This is a project done by a couple of Flatiron Students for educational purposes.</p>
        <p>We hope you enjoy!</p>

      </div>
    </div>
  </div>
</body>

app/views/application/account_type.html.erb
<h3>Create a Profile for:</h3>

<div class="btn-group">
  <%= button_to "Person", new_person_path, {method: 'get'}%>
  <%= button_to "Cat", new_cat_path, {method: 'get'}%>
  <%= button_to "Admin", new_admin_path, {method: 'get'}%>
</div>

app/views/application/index.html.erb
<div class="container">
<header class="jumbotron">

  <div class="container">

    <h1><span class="glyphicons glyphicons-cat"></span> Welcome to Purrfect Match</h1>
    <p>View potential adopters and kitties from all over the world!</p>

    <% if session[:person_id].nil? %>
      <p>
        <%= link_to "Create a Profile", new_person_path, class: "btn btn-primary btn-lg" %>
      </p>
    <% end %>

  </div>

</header>

<div class="container">
  <div class="row text-center">
    <%= form_tag profiles_path, :method => "get", :id => "search-form", :class => "form-control-md" do %>
      <div class="form-group" style="margin-bottom: 15px">
        <%= select_tag "search", options_for_select(["Person", "Cat"]), class: "form-control", style: "margin-bottom: 10px" %>
        <%= submit_tag "Search", :name => nil, class: "btn btn-info" %>
      </div>
    <% end %>
  </div>

  <div class="row text-center" style="margin-bottom: 10px">
    <%= link_to "Advanced Search", new_search_path, class: "btn btn-info" %>
  </div>
</div>


<div class="row text-center" style="display: flex; flex-wrap: wrap;">

  <% @profiles.each do |profile| %>

    <div class="col-md-3 col-sm-6">
      <div class="thumbnail">
        <%= image_tag("#{profile.image_url}") %>
        <div class="caption">
          <h4><%= profile.name %></h4>
        </div>
        <p>
          <%= link_to "More Info", "/#{profile.class.to_s.pluralize.downcase}/#{profile.id}", class: "btn btn-primary" %>
        </p>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/application/landing.html.erb
<body class="landing">
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div id="content">
					<h1 class="landing-text">Purrfect Match</h1>
					<h3 class="landing-text">The Only Human-Feline Dating App</h3>
					<hr class="landing-text">
					<%= link_to login_path, class: "btn btn-default btn-lg" do %>
						<i class="fa fa-paw" aria-hidden="true"></i> Get Started!
					<% end %>
				</div>
			</div>
		</div>
	</div>
</body>

app/views/cats/_form.html.erb
  <div style="width: 50%; margin: 25px auto;">

    <%= form_for @cat do |f| %>

    <ul>
      <% if @cat.errors.any? %>
        <% @cat.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      <% end %>
    </ul>

      <!-- Email -->
      <!-- <div class="form-group">
        <#%= f.label :email %>
        <#%= f.text_field :email, class: "form-control", placeholder: "Email" %>
      </div> -->

      <!-- Password -->
      <!-- <div class="form-group">
        <#%= f.label :password %>
        <#%= f.password_field :password, class: "form-control", placeholder: "Password" %>
      </div> -->

      <!-- Password Confirmation -->

      <!-- <div class="form-group">
        <#%= f.label :password_confirmation %>
        <#%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
      </div> -->

      <!-- <h2>Cat Info</h2> -->

      <!-- Name -->
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
      </div>

      <!-- Breed -->
      <div class="form-group">
        <%= f.label :breed %>
        <%= f.text_field :breed, min: 1, class: "form-control", placeholder: "Breed" %>
      </div>

      <!-- Age -->
      <div class="form-group">
        <%= f.label :age %>
        <%= f.number_field :age, min: 1, class: "form-control", placeholder: "Age" %>
      </div>


      <!-- Description -->
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", placeholder: "Description" %>
      </div>

      <!-- Sociability -->
      <div class="form-group">
        <%= f.label :sociability %>
        <%= f.text_field :sociability, class: "form-control", placeholder: "Sociability" %>
      </div>

      <!-- Temperament -->
      <div class="form-group">
        <%= f.label :temperament, "Temperament" %>
        <%= f.text_field :temperament, class: "form-control", placeholder: "Temperament" %>
      </div>


      <!-- Location -->
      <div class="form-group">
        <%= f.label :location %>
        <%= f.text_field :location, class: "form-control", placeholder: "Location" %>
      </div>

      <!-- Image URL -->
      <div class="form-group">
        <%= f.label :image_url %>
        <%= f.text_field :image_url, class: "form-control", placeholder: "Image URL" %>
      </div>

      <!-- Submit -->
      <div class="form-group">
        <%= f.submit class: "btn btn-lg btn-primary btn-block" %>
      </div>
    <% end %>
  </div>

app/views/cats/edit.html.erb
<div class="row">
  <h1 style="text-align: center;">Edit Cat</h1>

<%= render 'form' %>

</div>

app/views/cats/new.html.erb
<div class="row">
  <h1 style="text-align: center;">Create a New Cat</h1>

<%= render 'form' %>

</div>

app/views/cats/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3">

      <p class="Lead">Personal Info</p>

      <!-- Attributes -->
      <div class="list-group">
        <li class="list-group-item">
          Age: <%= @cat.age %>
        </li>
        <li class="list-group-item">
          Breed: <%= @cat.breed %>
        </li>
        <li class="list-group-item">Info 3</li>
      </div>


      <p class="Lead">Sponsors</p>

      <div class="list-group">
        <% @cat.persons.each do |person| %>
          <li class="list-group-item"><%= link_to person.name, person_path(person) %></li>
        <% end %>
      </div>
      <%= link_to "Return to Profiles", profiles_path, class: "btn btn-xs btn-primary"  %>
    </div>


    <div class="col-md-9">
      <div class="thumbnail">

        <%= image_tag @cat.image_url, class: "image-responsive" %>

        <div class="caption">
          <h4><a><%= @cat.name %></a></h4>
          <p><%= @cat.description %></p>

          <% if current_user && @cat.persons.include?(current_user) || current_user && current_user.admin? %>

            <%= link_to "Edit Profile", edit_cat_path(@cat), class: "btn btn-xs btn-warning" %>
            <div class="btn btn-xs btn-danger">
                <%= link_to "Delete Profile", cat_path(@cat), { method: :delete } %>
            </div>

          <% end %>

        </div>
      </div>
        <div class="row text-center">
          <%= link_to "Request Cat", "#", class: "btn btn-lg btn-success" %>
        </div>
    </div>
  </div>
</div>





<!-- <h1><#%= @cat.name %></h1>
Breed: <p><#%= @cat.breed %></p>
<p><#%= image_tag(@cat.image_url) %></p>
<h3>Description</h3>
<p><#%= @cat.description %></p>

<h2>Owner</h2>
<#%= link_to @cat.persons.first.name, person_path(@cat.persons.first) %>

<br>

<br>
<#%= link_to "Edit Profile", edit_cat_path(@cat) %> -->

<!-- <p><em>Submitted by <a href="/users/<#%= campground.author.id %>"><#%= campground.author.username %></a></em> <#%= moment(campground.createdAt).fromNow() %>.</p> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Purrfect Match</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- <#%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- <link rel="stylesheet" type="text/css" href="landing.css"> -->
</head>
<body>

	<nav class="navbar navbar-default">
	  <div class="container">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">Purrfect Match</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="/profiles">Home</a></li>
	        <li><a href="/about">About</a></li>
	      </ul>
	      <ul class="nav navbar-nav navbar-right">
					<% if session[:person_id].nil? %>
		        <li><a href="/people/new">Sign Up <i class="fa fa-user-plus" aria-hidden="true"></i></a></li>
					<% end %>

					<% if session[:person_id].nil? %>
						<li>
							<%= link_to(login_path) do %>
								Login <i class="fa fa-user" aria-hidden="true"></i></a>
							<% end %>
						</li>
					<% else %>
						<li>
							<%= link_to(logout_path, method: :delete) do %>
								Logout <i class="fa fa-user" aria-hidden="true"></i></a>
							<% end %>
						</li>

							<!-- <a href="/logout" method="post">Logout <i class="fa fa-user" aria-hidden="true"></i></a></li> -->
					<% end %>

	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container -->
	</nav>
	<div class="container">
		  <%= yield %>
			
	</div>

  <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
  </html>

app/views/layouts/previous.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Purrfect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_final.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3">

      <p class="Lead">Purrfect Match</p>

      <!-- Attributes -->
      <div class="list-group">
        <li class="list-group-item active">Info 1</li>
        <li class="list-group-item">Info 2</li>
        <li class="list-group-item">Info 3</li>
      </div>

    </div>

    <div class="col-md-9">
      <div class="thumbnail">

        <%= image_tag @person.image_url, class: "image-responsive" %>

        <div class="caption">
          <h4><a><%= @person.name %></a></h4>
          <p><%= @person.description %></p>

          <% if current_user && @person.id == current_user.id || current_user && current_user.admin? %>

            <%= link_to "Edit Profile", edit_person_path(@person), class: "btn btn-xs btn-warning" %>

            <%= link_to "Delete Profile", person_path(@person), class: "btn btn-xs btn-danger" { method: :delete } %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/people/edit.html.erb
<div class="row">
  <h1 style="text-align: center;">Edit Profile</h1>
  <div class="container">

 <% if flash[:error] %>
   <% flash.each do |key, value| %>
     <div class="alert alert-danger" role="alert">
       <%= content_tag :div, value, class: "flash #{key}" %>
     </div>
   <% end %>
 <% end %>
</div>

<%= render 'form' %>

</div>

app/views/people/new.html.erb
<div class="row">
  <h1 style="text-align: center;">Create New Profile</h1>
  <div class="container">

 <% if flash[:error] %>
   <% flash.each do |key, value| %>
     <div class="alert alert-danger" role="alert">
       <% value.each do |msg| %>
        <%= content_tag :div, msg, class: "flash #{key}" %>
       <% end %>
     </div>
   <% end %>
 <% end %>
</div>

    <%= render 'form'%>

</div>

app/views/people/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3">

      <p class="Lead">Personal Info</p>

      <!-- Attributes -->
      <div class="list-group">

          <li class="list-group-item">Age:
              <%= @person.age %>
          </li>
          <li class="list-group-item">Location:
              <%= @person.location %>
          </li>
          <li class="list-group-item">Cat Breed Preference:
              <%= @person.breed_pref %>
          </li>
          <li class="list-group-item">Cat Age Preference:
            From <%= @person.min_age_pref %> to <%= @person.max_age_pref %>
          </li>
          <li class="list-group-item">Cat Temperament Preference:
              <%= @person.temperament_pref %>
          </li>
      </div>


      <p class="Lead">My Cats</p>

      <div class="list-group">
        <% if @person.cats.empty? %>
          <li class="list-group-item"><%= "I don't have cats" %></li>
        <% else %>
          <% @person.cats.each do |cat| %>
            <li class="list-group-item"><%= link_to cat.name, cat_path(cat) %></li>
          <% end %>
        <% end %>
      </div>
      <%= link_to "Return to Profiles", profiles_path, class: "btn btn-xs btn-primary"  %>
    </div>

    <div class="col-md-9">
      <div class="thumbnail">

        <%= image_tag @person.image_url, class: "image-responsive" %>

        <div class="caption">
          <h4><a><%= @person.name %></a></h4>
          <p><%= @person.description %></p>

          <% if current_user && @person.id == current_user.id || current_user && current_user.admin? %>

            <%= link_to "Add a New Cat", new_cat_path, class: "btn btn-xs btn-primary" %>

            <%= link_to "Edit Profile", edit_person_path(@person), class: "btn btn-xs btn-warning" %>
            <div class="btn btn-xs btn-danger">
                <%= link_to "Delete Profile", person_path(@person), { method: :delete } %>
            </div>

          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

        <!-- <h1><#%= @person.name %></h1>
        Age: <p><#%= @person.age %></p> -->

    <!-- <div class="col-md-9">
      <div class="thumbnail">
        <p><#%= image_tag(@person.image_url), class: "image-responsive" %></p>

        <h1>Cats</h1>
        <% if @person.cats.empty? %>
          <#%= "I don't have cats" %>
        <% else %>
        <ul>
          <% @person.cats.each do |cat| %>
            <li><#%= link_to cat.name, cat_path(cat) %></li>
          <% end %>
        </ul>
        <% end %> -->



      <!-- <% if current_user && @person.id == current_user.id || current_user && current_user.admin %>
      <#%= link_to "Add a New Cat", new_cat_path, class: "btn btn-primary" %>
        <br>
        <br>
        <#%= link_to "Edit Profile", edit_person_path(@person), class: "btn btn-primary" %>
        <br>
        <br>
        <#%= link_to "Delete Profile", person_path(@person), { method: :delete } %>
      <% end %>
  </div>
</div> -->

app/views/searches/show.html.erb
<div class="container">
<header class="jumbotron">

  <div class="container">

    <h1><span class="glyphicons glyphicons-cat"></span> Welcome to Purrfect Match</h1>
    <p>View potential adopters and kitties from all over the world!</p>

      <p>
        <%= link_to "Back to All Profiles", profiles_path, class: "btn btn-primary btn-lg" %>
      </p>

  </div>

</header>

<!-- <div class="container">
  <div class="row text-center">
    <#%= form_tag profiles_path, :method => "get", :id => "search-form", :class => "form-control-md" do %>
      <div class="form-group" style="margin-bottom: 15px">
        <#%= select_tag "search", options_for_select(["Person", "Cat"]), class: "form-control", style: "margin-bottom: 10px" %>
        <#%= submit_tag "Search", :name => nil, class: "btn btn-info" %>
      </div>
    <#% end %>
  </div>

  <div class="row text-center" style="margin-bottom: 10px">
    <#%= link_to "Advanced Search", new_search_path, class: "btn btn-info" %>
  </div>
</div> -->


<div class="row text-center" style="display: flex; flex-wrap: wrap;">


  <% if @search.search_profiles.empty? %>
    <p class="lead" style="margin-left: 22px">Sorry! Nothing found</p>
  <% else %>
    <ul>
      <% @search.search_profiles.each do |profile| %>
        <!-- <li><#%= profile.name %></li> -->
        <div class="col-md-3 col-sm-6">
          <div class="thumbnail">
            <%= image_tag("#{profile.image_url}") %>
            <div class="caption">
              <h4><%= profile.name %></h4>
            </div>
            <p>
              <%= link_to "More Info", "/#{profile.class.to_s.pluralize.downcase}/#{profile.id}", class: "btn btn-primary" %>
            </p>
          </div>
        </div>
      <% end %>
    </ul>
  <% end %>

</div>

</div>